config/routes.rb
Rails.application.routes.draw do
   get 'scores/new'
   post 'scores/create'
   get 'scores/display'
   post 'scores/update'
   get 'favorites/index'
   get 'scores/index'
   get 'scores/result'
   
   get 'sessions/new'
   
   root 'pages#index'
   get 'pages/help'
   
   
   get '/login', to: 'sessions#new'
   post '/login', to: 'sessions#create'
   delete '/logout', to: 'sessions#destroy'
   
   resources 'users'
   resources 'topics'
   post '/favorites', to: 'favorites#create'
   
   get '/favorites', to: 'favorites#index'
  
  #For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :topic

end

app/models/player.rb
class Player < ApplicationRecord
end

app/models/point.rb
class Point < ApplicationRecord
 
end

app/models/topic.rb
class Topic < ApplicationRecord
    mount_uploader :image, ImageUploader
    
    validates :user_id, presence: true
    validates :description, presence: true
    validates :image, presence: true
    
    belongs_to :user
    has_many :favorites
    has_many :favorite_users, through: :favorites, source: 'user'
    end

app/models/user.rb
class User < ApplicationRecord
    validates :name,presence:true
    validates :email,presence:true
    validates :password,presence:true
    
    has_many :topics
    has_many :favorites
    has_many :favorite_topics, through: :favorites, source: 'topic'
    
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :null_session
    
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    
    def logged_in?
        !current_user.nil?
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
      @favorite_topic = current_user.favorite_topics
  end
  def create
      favorite = Favorite.new
      favorite.user_id = current_user.id
      favorite.topic_id = params[:topic_id]
      if favorite.save
          redirect_to topics_path, notice: 'お気に入りに登録しました'
          else
          redirect_to topics_path, notice: 'お気に入りに登録に失敗しました'
      end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
  def help
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
    def new
        @player = Player.new 
    end

    def create
        @player = Player.new(player_params)
        if @player.save
            redirect_to scores_display_path, notice: '登録が完了しました'
        else
            flash.now[:alert] = "登録に失敗しました"
            render :new
        end
    end

    def display
        @player = Player.last
        @point = Point.new
        gon.point_instance = Point.new
        gon.points = []
        gon.opponent_points = []
        gon.score_display_number = []
    end

    def update
        @point = Point.new
        @point.all_points = (params[:my_all_opint])
        @point.all_points_opponent = (params[:opponent_all_point])
        @point.score_display_number = (params[:score_display_numbers])
        @point.game_count = (params[:game_count])
        @point.save
    end

    def result
        @point_last = Point.last
        @point = Point.last(@point_last.game_count)
        gon.game_count = @point_last.game_count
        gon.game_count_array = []
        gon.score_display_number = []
        gon.all_points = []
        gon.all_points_opponent = []
        point_index = 2
        point_flg = @point_last.all_points.length-1
        flg = @point[gon.game_count.to_i-1].game_count.to_i
        while @point_last.game_count.to_i >= 0  do
            gon.game_count_array.unshift(@point[@point_last.game_count.to_i])
            @point_last.game_count = @point_last.game_count.to_i - 1
        end
        while flg >= 1 do
            gon.score_display_number.unshift(@point[flg-1].score_display_number)
            flg = flg-1
        end
        while point_flg >= point_index do
            gon.all_points.push(@point_last.all_points[point_index])
            gon.all_points_opponent.push(@point_last.all_points_opponent[point_index])
            point_index = point_index+5
        end
        @player = Player.last
    end

    def index 
    end

    private
    def player_params
        params.require(:player).permit(:baseline_player, :net_player,:baseline_player_opponent,:net_player_opponent,:Group_opponent,:Group,:Games_id)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
    
    def create
        user = User.find_by(email: params[:session][:email])
        if user && user.authenticate(params[:session][:password])
            log_in user
            redirect_to new_topic_path, alert: 'ログインに成功しました'
            else
            flash.now[:danger] = "ログインに失敗しました"
            render 'new'
        end
    end
    
    def destroy
        log_out
        redirect_to root_url
    end
    
private
    def log_in(user)
        session[:user_id] = user.id
    end
    
    def log_out
        session.delete(:user_id)
        @current_user = nil
    end
    
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
    def new
        @topic = Topic.new
    end
    
    def create
        if current_user.topics.create(topic_params)
            redirect_to topics_path, notice: '投稿に成功しました'
        else
            flash.now[:alert] = "投稿に失敗しました"
            render :new
        end
    end
    def index
        @topics = Topic.all.includes(:favorite_users)
    end

    private
    def topic_params
        params.require(:topic).permit(:image, :description)
    end
   
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end
    
    def create
        @user = User.new(user_params)
        if @user.save
            redirect_to root_path, notice: '登録が完了しました'
            else
            flash.now[:alert] = "登録に失敗しました"
            render :new
        end
    end
    
    private
    def user_params
        params.require(:user).permit(:name, :email,:password,:passwordconfirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    
    def logged_in?
        !current_user.nil?
    end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/index.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    <% @favorite_topics.each do |topic| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="topic-index-single">
            <h2 class="topic-author">
              <%= topic.user.name %>
            </h2>
            <%= image_tag topic.image.url %>
            <%= image_tag 'icons/comment.png', class: 'topic-index-icon' %>
            <p class="topic-text">
              <%= topic.description %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
          <!DOCTYPE html>
<html>
  <head>
    <title>KIROKU</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <%= include_gon %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Wendy+One" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Noto+Serif|Wendy+One" rel="stylesheet">
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-danger">
        <%= flash[:alert] %>
      </div>
    <% end %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top navbar-transparent">
  <div class="container">
    <%= link_to root_path do %>
      <span><%= image_tag "icons/logo.png", class: "navbar-brand" %></span>
    <% end %>
    <ul class="nav navbar-nav navbar-right">
      <% if logged_in? %>
        <li>
          <%= link_to scores_display_path do %>
            <%= image_tag "icons/score.png" %>
          <% end %>
        </li>
        <li>
          <%= link_to user_path(@current_user) do %>
            <%= image_tag "icons/profile.png" %>
          <% end %>
        </li>
        <li>
          <%= link_to logout_path, method: :delete do %>
            <%= image_tag "icons/logout.png" %>
          <% end %>
        </li>
      <% else %>
        <li>
          <%= link_to "#" do %>
            <%= image_tag "icons/register.png" %>
          <% end %>
        </li>
        <li>
          <%= link_to login_path do %>
            <%= image_tag "icons/login.png" %>
          <% end %>
        </li>
        <li>
          <%= link_to scores_display_path do %>
            <%= image_tag "icons/register.png" %>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>
   <% if flash[:notice] %>
     <div class="alert alert-success">
       <%= flash[:notice] %>
     </div>
   <% end %>
   <% if flash[:alert] %>
     <div class="alert alert-danger">
       <%= flash[:alert] %>
     </div>
   <% end %>

    <%= yield %>
  </body>
  
</html>

app/views/pages/help.html.erb
<div class="features-boxed">
    <div class="container">
        <div class="row">
            <div class="intro">
                <h2 class="text-center">pechakuchaってなに？</h2>
                <h4 class="text-center">ペチャクチャは皆が自由にスポーツについて話すことができ、皆が自由にスポーツノートを書くことができるアプリケーションです。</h4>
            </div>
        </div>
        <div class="row justify-content-center features">
            <div class="col-sm-6 col-md-5 col-lg-4 item">
                <div class="box"><i class="fa fa-map-marker icon"></i>
                    <h3 class="name">Write your thoughts on the sports note more and more!</h3>
                    <p class="description">どんどん思ったことをスポーツノートに書いて！</p><a href="/notes/new" class="learn-more">Learn more »</a></div>
            </div>
            <div class="col-sm-6 col-md-5 col-lg-4 item">
                <div class="box"><i class="fa fa-clock-o icon"></i>
                    <h3 class="name">Please tweet! Like a twitter</h3>
                    <p class="description">どんどん思ったことを呟いて！Twitterみたいに！</p><a href="/tweets/new" class="learn-more">Learn more »</a></div>
            </div>
            <div class="col-sm-6 col-md-5 col-lg-4 item">
                <div class="box"><i class="fa fa-list-alt icon"></i>
                    <h3 class="name">Let's make friends with many people!</h3>
                    <p class="description">どんどんフォローして多くの人と友達になろう！</p><a href="/pages#index" class="learn-more">Learn more »</a></div>
            </div>
        </div>
        <div class="row self-produce">
            <div class="col-md-12 text-center self-produce">
                <h2 class="self-introduction">・SELF　INTRODUCTION・</h2>
            </div>
        </div>
        <div class="row row4">
            <div class="col-md-4 self-introduction-box">
                <div class="box">
                    <h3 class="text-center font">Basic information</h3>
                    <h4 class="text-center font"> ・Developer・</h4><p class="text-center my-information">GAKU</p>
                    <h4 class="text-center font"> ・Age・</h4><p class="text-center my-information">21</p>
                    <h4 class="text-center font"> ・Job category・</h4><p class="text-center my-information">student</p>
                    <h4 class="text-center font"> ・Used programming language・</h4><p class="text-center my-information">html　css　ruby　javascript</p>
                    <h4 class="text-center font"> ・Used Framework・</h4><p class="text-center my-information">bootstrap　JQuery　Rubyonrails </p>
                    <h4 class="text-center font"> ・Production period・</h4><p class="text-center my-information">about　1month</p>
                    <h4 class="text-center font"> ・Learning period・</h4><p class="text-center my-information">3month</p>
                </div>
            </div>
            <div class="col-md-8 self-introduction-box">
                <div class="box">
                    <h3 class="text-center font">Other　information </h3>
                    <h4 class="text-center font">&#x1f447;My SNS acount&#x1f447;</h4>
                    <h5 class="text-center font">please　follow　me!!! </h5>
                        <div class="social text-center">
                            <a href="https://twitter.com/GeminiTennis?lang=ja"><%= image_tag 'icons/twitter.png', class: 'topic-index-icon' %></a>
                            <a href="https://www.instagram.com/tennis_0521/"><%= image_tag 'icons/instagram.png', class: 'topic-index-icon' %></a>
                            <p class="text-center">自分の初めて作ったWebアプリケーションです。全然立派なものではありませんが３ヶ月間没頭しました。今後は、２作目のWebアプリケーションの作成に取り掛かろうと思います。
                            何か質問などがあれば上記のアカウントまで連絡ください！！！ </p>
                        </div>

                </div>
            </div>
        </div>
    </div>
</div>

app/views/pages/index.html.erb
<div class="top-hero-wrapper text-center">
  <div class="container top-hero-container">
    <h1 class="text-navy">OK! Let's get for a trip</h1>
    <h2 class="text-navy">TRIPROUTES is a service that you can share the travel report.</h2>
    <div class="row">
      <div class="col-md-offset-3 col-md-3">
        <%= link_to 'Sign in', 'users/new', class: 'btn btn-block btn-white' %>
      </div>
      <div class="col-md-3">
        <%= link_to 'Log in', 'login',class: 'btn btn-block btn-white' %>
      </div>
    </div>
  </div>
</div>

app/views/scores/index.html.erb
<h1>ChartSample#index</h1>
<p>Find me in app/views/chart_sample/index.html.erb</p>

<canvas id="myChart" width="400" height="400"></canvas> ←★追記
<script>draw_graph();</script> ←★追記

app/views/scores/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <h1 class="text-center">This is page that enter player's basic information<h1>
        </div>
    </div>
    <div class="row">
        <div class="col-md-5">
            <h3 class="text-center">・Player・</h3>
                <%= form_for @player, url: scores_create_path do |f| %>
                    <div class="form-group">
                        <%= f.label :Group, class: 'text-white' %>
                        <%= f.text_field :Group, class: 'form-control' %>
                    </div>
                    <div class="form-group">
                        <%= f.label :baseline_player, class: 'text-white' %>
                        <%= f.text_field :baseline_player, class: 'form-control' %>
                    </div>
                    <div class="form-group">
                        <%= f.label :net_player, class: 'text-white' %>
                        <%= f.text_field :net_player, class: 'form-control' %>
                    </div>
        </div>
        <div class="col-md-2">
            <h4 class="text-center">VS</h4>
            <%= f.submit "submit", class: 'btn-block btn-white' %>
        </div>
        <div class="col-md-5">
            <h3 class="text-center">・Opponent・</h3>
                    <div class="form-group">
                        <%= f.label :Group_opponent, class: 'text-white' %>
                        <%= f.text_field :Group_opponent, class: 'form-control' %>
                    </div>
                    <div class="form-group">
                        <%= f.label :baseline_player_opponent, class: 'text-white' %>
                        <%= f.text_field :baseline_player_opponent, class: 'form-control' %>
                    </div>
                    <div class="form-group">
                        <%= f.label :net_player_opponent, class: 'text-white' %>
                        <%= f.text_field :net_player_opponent, class: 'form-control' %>
                    </div>
                <% end %>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 col-md-offset-3 box">

        </div>
    </div>
</div>

app/views/topics/index.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    <% @topics.each do |topic| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="topic-index-single">
            <h2 class="topic-author">
              <%= topic.user.name %>
            </h2>
            <%= image_tag topic.image.url %>
              <% if !topic.favorite_users.include?(current_user) %>
                <%= link_to favorites_path(topic_id: topic.id), method: :post do %>
                  <%= image_tag 'icons/heart-black.png', class: 'topic-index-icon' %>
                <% end %>
              <% end %>
            <%= image_tag 'icons/comment.png', class: 'topic-index-icon' %>
            <p class="topic-text">
              <%= topic.description %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/topics/new.html.erb
<div class="topic-new-wrapper" >
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Add Picture</h1>
        <%= form_for @topic do |f| %>
          <div class="form-group">
            <%= f.label :image %>
            <%= f.file_field :image%>
          </div>

          <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description, class: 'form-control' %>
          </div>

          <%= f.submit '投稿', class: 'btn btn-black btn-block' %>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="users-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 users-new-container">
        <h1 class="text-center text-white">Sign in</h1>
        <%= form_for @user do |f| %>
          <div class="form-group">
            <%= f.label :name, class: 'text-white' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :email, class: 'text-white' %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password, class: 'text-white' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password_confirmation, class: 'text-white' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>

          <%= f.submit "register", class: 'btn-block btn-white' %>
        <% end %>
        <%= link_to 'Login from here', '#',class: 'text-white' %>
      </div>
    </div>
  </div>
</div>